"""
project_data.py

Small hand-created project catalogue used by the Project Recommendations page.
Project careers and skills intentionally match the existing career_data.py values.
"""

PROJECT_DATA = [
    {
        "project_name": "Student Performance Prediction",
        "description": "Predict student outcomes from attendance, study habits, and assessment history.",
        "target_careers": ["Data Scientist", "Machine Learning Engineer"],
        "required_skills": ["Python", "Pandas", "Statistics", "Machine Learning"],
        "difficulty": "Intermediate",
        "skills_gained": ["Feature Engineering", "Model Evaluation", "Data Visualization"],
    },
    {
        "project_name": "Customer Churn Prediction",
        "description": "Identify customers at risk of leaving and explain the strongest churn signals.",
        "target_careers": ["Data Scientist", "Machine Learning Engineer"],
        "required_skills": ["Python", "Pandas", "SQL", "Machine Learning"],
        "difficulty": "Intermediate",
        "skills_gained": ["Classification", "Feature Engineering", "Model Evaluation"],
    },
    {
        "project_name": "Sales Forecasting",
        "description": "Forecast future sales and present trends in a clear business report.",
        "target_careers": ["Data Analyst", "Data Scientist"],
        "required_skills": ["Python", "Pandas", "Statistics", "Data Visualization"],
        "difficulty": "Intermediate",
        "skills_gained": ["Time-Series Analysis", "Forecasting", "Data Storytelling"],
    },
    {
        "project_name": "Customer Segmentation",
        "description": "Group customers by behavior to support more focused marketing decisions.",
        "target_careers": ["Data Scientist", "Data Analyst"],
        "required_skills": ["Python", "Pandas", "Statistics", "Machine Learning"],
        "difficulty": "Intermediate",
        "skills_gained": ["Clustering", "Feature Engineering", "Insight Communication"],
    },
    {
        "project_name": "Sales Dashboard",
        "description": "Build an interactive dashboard that turns sales records into actionable insights.",
        "target_careers": ["Data Analyst"],
        "required_skills": ["SQL", "Excel", "Data Visualization", "Power BI"],
        "difficulty": "Beginner",
        "skills_gained": ["Dashboard Design", "KPI Selection", "Data Storytelling"],
    },
    {
        "project_name": "Student Performance Analytics",
        "description": "Explore academic trends and identify the factors associated with stronger outcomes.",
        "target_careers": ["Data Analyst"],
        "required_skills": ["Excel", "SQL", "Statistics", "Data Visualization"],
        "difficulty": "Beginner",
        "skills_gained": ["Exploratory Analysis", "Reporting", "Data Storytelling"],
    },
    {
        "project_name": "House Price Prediction",
        "description": "Estimate property prices from location, size, and other housing features.",
        "target_careers": ["Machine Learning Engineer", "Data Scientist"],
        "required_skills": ["Python", "Pandas", "Statistics", "Machine Learning"],
        "difficulty": "Beginner",
        "skills_gained": ["Regression", "Feature Engineering", "Model Evaluation"],
    },
    {
        "project_name": "Credit Risk Prediction",
        "description": "Classify loan applications by risk while examining fairness and model quality.",
        "target_careers": ["Machine Learning Engineer", "Data Scientist"],
        "required_skills": ["Python", "SQL", "Statistics", "Machine Learning"],
        "difficulty": "Advanced",
        "skills_gained": ["Classification", "Model Evaluation", "Responsible ML"],
    },
    {
        "project_name": "Recommendation System",
        "description": "Recommend books, courses, or products based on user preferences and history.",
        "target_careers": ["Machine Learning Engineer", "Data Scientist"],
        "required_skills": ["Python", "Machine Learning", "Statistics", "Data Structures"],
        "difficulty": "Advanced",
        "skills_gained": ["Similarity Methods", "Ranking", "Model Deployment"],
    },
    {
        "project_name": "Image Classification",
        "description": "Train a model that recognizes categories in a labelled image collection.",
        "target_careers": ["Machine Learning Engineer"],
        "required_skills": ["Python", "Machine Learning", "Deep Learning", "Model Deployment"],
        "difficulty": "Advanced",
        "skills_gained": ["Computer Vision", "Neural Networks", "Model Evaluation"],
    },
    {
        "project_name": "Job Portal",
        "description": "Create a full-stack platform for browsing, searching, and applying to jobs.",
        "target_careers": ["Full Stack Developer"],
        "required_skills": ["HTML/CSS", "JavaScript", "React", "Node.js", "SQL"],
        "difficulty": "Advanced",
        "skills_gained": ["Authentication Flows", "REST APIs", "Database Design"],
    },
    {
        "project_name": "Student Management System",
        "description": "Manage student profiles, attendance, courses, and results through a web application.",
        "target_careers": ["Full Stack Developer"],
        "required_skills": ["HTML/CSS", "JavaScript", "SQL", "REST APIs"],
        "difficulty": "Intermediate",
        "skills_gained": ["CRUD Workflows", "Database Design", "Form Validation"],
    },
    {
        "project_name": "Event Management Platform",
        "description": "Let users discover events, reserve places, and manage event details online.",
        "target_careers": ["Full Stack Developer"],
        "required_skills": ["HTML/CSS", "JavaScript", "React", "Git"],
        "difficulty": "Intermediate",
        "skills_gained": ["Component Design", "REST APIs", "Deployment"],
    },
    {
        "project_name": "Cloud File Storage System",
        "description": "Design a secure file upload and sharing service with cloud storage.",
        "target_careers": ["Cloud Engineer"],
        "required_skills": ["Cloud Computing", "Linux", "Python", "Security Basics"],
        "difficulty": "Intermediate",
        "skills_gained": ["Object Storage", "Access Control", "Monitoring"],
    },
    {
        "project_name": "Serverless Web Application",
        "description": "Deploy a small event-driven web app using managed cloud services.",
        "target_careers": ["Cloud Engineer", "Full Stack Developer"],
        "required_skills": ["Cloud Computing", "JavaScript", "REST APIs", "Git"],
        "difficulty": "Advanced",
        "skills_gained": ["Serverless Architecture", "CI/CD", "Cloud Deployment"],
    },
    {
        "project_name": "Cloud Monitoring Dashboard",
        "description": "Track service health, resource usage, and alerts in a cloud environment.",
        "target_careers": ["Cloud Engineer"],
        "required_skills": ["Cloud Computing", "Linux", "Networking", "Python"],
        "difficulty": "Intermediate",
        "skills_gained": ["Observability", "Alerting", "Incident Response"],
    },
    {
        "project_name": "Phishing URL Detection",
        "description": "Classify suspicious links and explain the signals that indicate phishing.",
        "target_careers": ["Cybersecurity Analyst", "Machine Learning Engineer"],
        "required_skills": ["Python", "Networking", "Security Basics", "Machine Learning"],
        "difficulty": "Intermediate",
        "skills_gained": ["Threat Detection", "Feature Engineering", "Security Reporting"],
    },
    {
        "project_name": "Network Intrusion Detection",
        "description": "Analyze network traffic patterns to flag potentially malicious activity.",
        "target_careers": ["Cybersecurity Analyst"],
        "required_skills": ["Networking", "Linux", "Security Basics", "Python"],
        "difficulty": "Advanced",
        "skills_gained": ["Traffic Analysis", "Detection Rules", "Incident Response"],
    },
]
